[colors]
draw_bold_text_with_bright_colors = true

# (Github Dark High Contrast) Colors for Alacritty

# Default colors
[colors.primary]
background = '#0a0c10'
foreground = '#f0f3f6'

# Cursor colors
[colors.cursor]
text = '#0a0c10'
cursor = '#f0f3f6'

# Normal colors
[colors.normal]
black = '#7a828e'
red = '#ff9492'
green = '#26cd4d'
yellow = '#f0b72f'
blue = '#71b7ff'
magenta = '#cb9eff'
cyan = '#39c5cf'
white = '#d9dee3'

# Bright colors
[colors.bright]
black = '#9ea7b3'
red = '#ffb1af'
green = '#4ae168'
yellow = '#f7c843'
blue = '#91cbff'
magenta = '#cb9eff'
cyan = '#39c5cf'
white = '#d9dee3'

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "DejaVuSansM Nerd Font Mono"

[font.offset]
x = 0
y = 2

[shell]
program = "/usr/bin/fish"

[window]
dynamic_title = false
startup_mode = "Maximized"
