import = ["~/.config/alacritty/themes/mountain.toml"]

[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[window]
dynamic_title = false
startup_mode = "Maximized"

[font]
size = 10

[font.normal]
family = "DejaVuSansM Nerd Font Mono"

[font.offset]
x = 0
y = 2

[colors]
draw_bold_text_with_bright_colors = true
