theme = "solarized_dark"

[editor]
cursorline = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
"C-z" = 'no_op'
"C-k" = "goto_prev_paragraph"
"C-j" = "goto_next_paragraph"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal."space"]
"c" = ":buffer-close"
